/* Semantic custom-input expansion, mandatory meals, and a strict 08:00-21:00 activity window. */
const installActivityWindowPlanner=()=>{
if(window.pmActivityWindowPlannerInstalled)return;
window.pmActivityWindowPlannerInstalled=true;
const ACTIVITY_START_HOUR=8,ACTIVITY_END_HOUR=21;
const activityBounds=d=>{let start=new Date(d),end=new Date(d);start.setHours(ACTIVITY_START_HOUR,0,0,0);end.setHours(ACTIVITY_END_HOUR,0,0,0);return{start,end}};
const isCategoryActivityInWindow=e=>{let bounds=activityBounds(e.start);return e.start>=bounds.start&&e.end<=bounds.end};
const concepts=[
{r:/물고기|해양생물|바닷속|상어|돌고래|fish|marine life|underwater|shark|dolphin|魚|海洋生物|鲨鱼|海豚/i,p:[['Busan Sea Life Aquarium',35,100,98],['Busan National Maritime Museum Aquarium',25,80,90]]},
{r:/별|천문|우주|행성|야경|전망|star|space|planet|astronomy|night view|observatory|星|宇宙|夜景|展望/i,p:[['Geumnyeonsan Observatory',28,90,92],['Hwangnyeongsan Observatory',30,90,90]]},
{r:/만들기|공예|그림|도자|체험|craft|make|painting|pottery|ceramic|手作|工芸|陶芸|手工|陶瓷/i,p:[['Busan Pottery Experience Center',30,100,91],['F1963 Creative Space',30,90,86]]},
{r:/책|독서|서점|문학|book|reading|bookstore|literature|本|読書|書店|书|阅读/i,p:[['Bosudong Book Alley',15,90,95],['F1963 Library',30,90,86]]},
{r:/춤|댄스|공연|연극|영화|콘서트|dance|performance|theater|cinema|concert|踊り|公演|映画|舞蹈|演出|电影/i,p:[['Busan Cinema Center',32,120,94],['Busan Cultural Center',28,120,89]]},
{r:/운동|스포츠|축구|야구|자전거|클라이밍|sports?|football|baseball|cycling|climbing|スポーツ|野球|自転車|运动|棒球|自行车/i,p:[['Sajik Sports Complex',30,120,93],['Gwangalli SUP Zone',28,100,87]]},
{r:/동물|새|고양이|강아지|animal|bird|cat|dog|動物|鳥|猫|犬|动物|鸟/i,p:[['Samjung The Park Zoo',30,120,90],['Nakdong Estuary Eco Center',35,100,88]]},
{r:/꽃|정원|숲|식물|자연|flower|garden|forest|plant|花|庭園|森|植物|花园/i,p:[['Busan Citizens Park',25,100,91],['Ahopsan Forest',40,110,89]]}
];
const original=$('#analyzeCustom'),input=$('#customCategory'),result=$('#customResult');
const redraw=()=>{let box=$('#customCategoryChips');if(!box)return;box.innerHTML=pmCustomCategories.map((c,i)=>`<button class="active" data-i="${i}">${c.query} ×</button>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{pmCustomCategories.splice(+b.dataset.i,1);redraw()})};
if(original&&input){const prior=original.onclick;async function semanticAdd(){let raw=input.value.trim();if(raw.length<2||/[ㄱ-ㅎㅏ-ㅣ]$/.test(raw)){result.textContent=lang==='ko'?'단어가 완성되지 않았습니다. 다시 입력해 주세요.':'Please enter a complete word.';return}let match=concepts.find(c=>c.r.test(raw));if(match){pmCustomCategories.push({id:'semantic-'+Date.now(),query:raw,candidates:match.p});result.textContent=(lang==='ko'?'관련 활동 장소를 찾았습니다: ':'Related activity places found: ')+match.p.map(p=>p[0]).join(', ');input.value='';redraw();return}await prior.call(original)}original.onclick=semanticAdd;input.onkeydown=e=>{if(e.key==='Enter')semanticAdd()}}
function planner(){
if(!chosen.length&&!pmCustomCategories.length){show(t('noCat'),'','');return}
let info=available(),start=new Date(info.start),end=new Date(start.getTime()+info.left*60000),cruiseStart=new Date(Math.max(start.getTime(),end.getTime()-3600000)),cursor=new Date(start),events=[],used=new Set(),food=[...places.food].sort(()=>Math.random()-.5);
const dayCode=d=>['Su','Mo','Tu','We','Th','Fr','Sa'][d.getDay()],clock=s=>{let [h,m]=s.split(':').map(Number);return h*60+(m||0)},isOpen=(rule,startAt,endAt)=>{if(!rule)return true;if(rule==='24/7')return true;let parts=rule.split(';').map(x=>x.trim()),code=dayCode(startAt),minute=startAt.getHours()*60+startAt.getMinutes(),finish=endAt.getHours()*60+endAt.getMinutes();return parts.some(part=>{if(/off|closed/i.test(part))return false;let times=part.match(/(\d{1,2}:\d{2})-(\d{1,2}:\d{2})/);if(!times)return false;let days=part.slice(0,part.indexOf(times[0])).trim();if(days&&days!=='Mo-Su'){let range=days.match(/(Mo|Tu|We|Th|Fr|Sa|Su)-(Mo|Tu|We|Th|Fr|Sa|Su)/),list=['Mo','Tu','We','Th','Fr','Sa','Su'];if(range){let a=list.indexOf(range[1]),b=list.indexOf(range[2]),i=list.indexOf(code);if(a<=b?i<a||i>b:i>b&&i<a)return false}else if(!days.split(',').map(x=>x.trim()).includes(code))return false}return minute>=clock(times[1])&&finish<=clock(times[2])})};
let pool=pmCustomCategories.flatMap(c=>c.candidates.map(p=>({name:p[0],travel:Math.ceil(p[1]*1.3+10),stay:p[2]||80,score:p[3]||80,opening:p[4]||null,custom:true,category:c.query}))).concat(chosen.filter(k=>k!=='food').flatMap(k=>(places[k]||[]).map(p=>({name:p[0],travel:Math.ceil(p[1]*1.3+10),stay:70,score:75+Math.random()*20}))));
if(chosen.includes('food'))pool.push(...food.map(p=>({name:p[0],travel:Math.ceil(p[1]*1.3+10),stay:60,score:75+Math.random()*20,extraFood:true})));
let meals=[];for(let day=new Date(start.getFullYear(),start.getMonth(),start.getDate());day<end;day.setDate(day.getDate()+1))[8,13,19].forEach((h,i)=>{let preferred=new Date(day);preferred.setHours(h,0,0,0);let windowStart=new Date(preferred.getTime()-3600000),windowEnd=new Date(preferred.getTime()+3600000),at=preferred<start?new Date(start):preferred;if(windowEnd>=start&&windowStart<cruiseStart&&at<cruiseStart&&h>=ACTIVITY_START_HOUR&&h<ACTIVITY_END_HOUR)meals.push({at,label:i===0?'아침밥':i===1?'점심밥':'저녁밥',preferred})});
let mi=0,active=0;
while(cursor<cruiseStart){let {start:dayStart,end:dayEnd}=activityBounds(cursor);if(cursor<dayStart||cursor>=dayEnd){let wake=new Date(cursor);if(cursor>=dayEnd)wake.setDate(wake.getDate()+1);wake.setHours(ACTIVITY_START_HOUR,0,0,0);if(wake>cruiseStart)wake=new Date(cruiseStart);events.push({type:'sleep',start:new Date(cursor),end:wake,name:lang==='ko'?'휴식 및 취침 시간':'Rest and sleep time'});cursor=wake;active=0;continue}while(meals[mi]&&cursor>new Date(meals[mi].preferred.getTime()+3600000))mi++;let meal=meals[mi];if(meal&&cursor>=meal.at){let p=food[mi%food.length],finish=new Date(cursor.getTime()+75*60000),mealEvent={type:'meal',start:new Date(cursor),end:finish,name:placeName([p[0]]),meta:lang==='ko'?`${meal.label} 추천 · ${String(meal.preferred.getHours()).padStart(2,'0')}:00 기준 ±1시간`:`Meal recommendation · within 1 hour of ${String(meal.preferred.getHours()).padStart(2,'0')}:00`};if(finish<=cruiseStart&&isCategoryActivityInWindow(mealEvent)){events.push(mealEvent);cursor=finish;mi++;active=0;continue}mi++;continue}
let remaining=Math.floor((cruiseStart-cursor)/60000),nextMeal=meals[mi]?.at,boundary=new Date(Math.min(cruiseStart.getTime(),dayEnd.getTime(),nextMeal?.getTime()||Infinity)),fit=pool.filter(x=>{let visitStart=new Date(cursor.getTime()+x.travel*60000),visitEnd=new Date(visitStart.getTime()+x.stay*60000);return!used.has(x.name)&&x.travel+x.stay<=remaining&&(!x.extraFood||(cursor.getHours()>=ACTIVITY_START_HOUR&&cursor.getHours()<ACTIVITY_END_HOUR))&&visitEnd<=boundary&&isOpen(x.opening,visitStart,visitEnd)}).sort((a,b)=>b.score-a.score||a.travel-b.travel)[0];
if(!fit){let target=boundary;if(target>cursor)events.push({type:'rest',start:new Date(cursor),end:new Date(target),name:lang==='ko'?'휴식 시간':'Rest time'});cursor=new Date(target);continue}
if(active>=150&&cursor.getTime()+600000+(fit.travel+fit.stay)*60000<=boundary.getTime()){let r=new Date(cursor.getTime()+600000);events.push({type:'rest',start:new Date(cursor),end:r,name:lang==='ko'?'휴식 시간':'Rest time'});cursor=r;active=0;continue}
let finish=new Date(cursor.getTime()+(fit.travel+fit.stay)*60000),hours=fit.opening?(lang==='ko'?` · 운영시간 ${fit.opening}`:` · Opening hours ${fit.opening}`):(fit.custom?(lang==='ko'?' · 운영시간 정보 없음':' · Opening hours unavailable'):''),activityEvent={type:fit.extraFood?'meal':'place',start:new Date(cursor),end:finish,name:fit.custom?fit.name:placeName([fit.name]),meta:(fit.custom?`${lang==='ko'?'직접 입력 카테고리':'Custom category'}: ${fit.category}`:(lang==='ko'?'이동 및 활동':'Travel and activity'))+hours};if(!isCategoryActivityInWindow(activityEvent)){events.push({type:'sleep',start:new Date(cursor),end:dayEnd,name:lang==='ko'?'휴식 및 취침 시간':'Rest and sleep time'});cursor=dayEnd;active=0;continue}used.add(fit.name);events.push(activityEvent);cursor=finish;active+=fit.travel+fit.stay}
events.push({type:'cruise',start:cruiseStart,end,name:lang==='ko'?'크루즈로 이동':'Return to the cruise'});
let last='',f=d=>`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`,rows=events.map((e,i)=>{let key=`${e.start.getFullYear()}-${e.start.getMonth()}-${e.start.getDate()}`,date=key!==last?`${e.start.getFullYear()}.${e.start.getMonth()+1}.${e.start.getDate()} `:'';last=key;return `<div class="detail-row ${e.type}"><span>${e.type==='meal'?'●':e.type==='rest'?'Ⅱ':e.type==='sleep'?'☾':e.type==='cruise'?'↗':i+1}</span><div><strong>${date}${f(e.start)}–${f(e.end)} · ${e.name}</strong><p>${e.meta||''}</p></div></div>`}).join('');show(t('route'),lang==='ko'?'카테고리 활동 08:00–21:00 · 그 외 휴식 및 취침':'Category activities 08:00–21:00 · rest and sleep outside these hours',rows)}
$('#generatePlan').onclick=planner;$('#refreshRoute').onclick=planner;['#generatePlan','#refreshRoute'].forEach(selector=>{let button=$(selector);button.disabled=false;button.removeAttribute('aria-busy')})
};
const scheduleActivityWindowPlanner=()=>{let navigation=performance.getEntriesByType?.('navigation')?.[0],elapsed=navigation?.loadEventEnd?performance.now()-navigation.loadEventEnd:0;setTimeout(installActivityWindowPlanner,Math.max(0,1900-elapsed))};
document.readyState==='complete'?scheduleActivityWindowPlanner():window.addEventListener('load',()=>setTimeout(installActivityWindowPlanner,1900),{once:true});
